# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1beta1_virtual_machine_cluster_preference import V1beta1VirtualMachineClusterPreference


class TestV1beta1VirtualMachineClusterPreference(unittest.TestCase):
    """ V1beta1VirtualMachineClusterPreference unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1VirtualMachineClusterPreference(self):
        """
        Test V1beta1VirtualMachineClusterPreference
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1beta1_virtual_machine_cluster_preference.V1beta1VirtualMachineClusterPreference()
        pass


if __name__ == '__main__':
    unittest.main()
