# coding: utf-8

"""
    KubeVirt API, 

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_label_selector import V1LabelSelector


class TestV1LabelSelector(unittest.TestCase):
    """ V1LabelSelector unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1LabelSelector(self):
        """
        Test V1LabelSelector
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_label_selector.V1LabelSelector()
        pass


if __name__ == '__main__':
    unittest.main()
