# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.io_k8s_apimachinery_pkg_apis_meta_v1_condition import IoK8sApimachineryPkgApisMetaV1Condition


class TestIoK8sApimachineryPkgApisMetaV1Condition(unittest.TestCase):
    """ IoK8sApimachineryPkgApisMetaV1Condition unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1Condition(self):
        """
        Test IoK8sApimachineryPkgApisMetaV1Condition
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.io_k8s_apimachinery_pkg_apis_meta_v1_condition.IoK8sApimachineryPkgApisMetaV1Condition()
        pass


if __name__ == '__main__':
    unittest.main()
