# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_virtual_machine_instance_file_system_disk import V1VirtualMachineInstanceFileSystemDisk


class TestV1VirtualMachineInstanceFileSystemDisk(unittest.TestCase):
    """ V1VirtualMachineInstanceFileSystemDisk unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1VirtualMachineInstanceFileSystemDisk(self):
        """
        Test V1VirtualMachineInstanceFileSystemDisk
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_virtual_machine_instance_file_system_disk.V1VirtualMachineInstanceFileSystemDisk()
        pass


if __name__ == '__main__':
    unittest.main()
