# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.io_k8s_api_core_v1_exec_action import IoK8sApiCoreV1ExecAction


class TestIoK8sApiCoreV1ExecAction(unittest.TestCase):
    """ IoK8sApiCoreV1ExecAction unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1ExecAction(self):
        """
        Test IoK8sApiCoreV1ExecAction
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.io_k8s_api_core_v1_exec_action.IoK8sApiCoreV1ExecAction()
        pass


if __name__ == '__main__':
    unittest.main()
