# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_qemu_guest_agent_ssh_public_key_access_credential_propagation import V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation


class TestV1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation(unittest.TestCase):
    """ V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation(self):
        """
        Test V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_qemu_guest_agent_ssh_public_key_access_credential_propagation.V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation()
        pass


if __name__ == '__main__':
    unittest.main()
