# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1alpha1_virtual_machine_pool_opportunistic_scale_in_strategy import V1alpha1VirtualMachinePoolOpportunisticScaleInStrategy


class TestV1alpha1VirtualMachinePoolOpportunisticScaleInStrategy(unittest.TestCase):
    """ V1alpha1VirtualMachinePoolOpportunisticScaleInStrategy unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1VirtualMachinePoolOpportunisticScaleInStrategy(self):
        """
        Test V1alpha1VirtualMachinePoolOpportunisticScaleInStrategy
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1alpha1_virtual_machine_pool_opportunistic_scale_in_strategy.V1alpha1VirtualMachinePoolOpportunisticScaleInStrategy()
        pass


if __name__ == '__main__':
    unittest.main()
