# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1beta1_data_volume_source import V1beta1DataVolumeSource


class TestV1beta1DataVolumeSource(unittest.TestCase):
    """ V1beta1DataVolumeSource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1DataVolumeSource(self):
        """
        Test V1beta1DataVolumeSource
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1beta1_data_volume_source.V1beta1DataVolumeSource()
        pass


if __name__ == '__main__':
    unittest.main()
