# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1alpha2_firmware_preferences import V1alpha2FirmwarePreferences


class TestV1alpha2FirmwarePreferences(unittest.TestCase):
    """ V1alpha2FirmwarePreferences unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha2FirmwarePreferences(self):
        """
        Test V1alpha2FirmwarePreferences
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1alpha2_firmware_preferences.V1alpha2FirmwarePreferences()
        pass


if __name__ == '__main__':
    unittest.main()
