# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.k8s_io_apimachinery_pkg_apis_meta_v1_fields_v1 import K8sIoApimachineryPkgApisMetaV1FieldsV1


class TestK8sIoApimachineryPkgApisMetaV1FieldsV1(unittest.TestCase):
    """ K8sIoApimachineryPkgApisMetaV1FieldsV1 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8sIoApimachineryPkgApisMetaV1FieldsV1(self):
        """
        Test K8sIoApimachineryPkgApisMetaV1FieldsV1
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.k8s_io_apimachinery_pkg_apis_meta_v1_fields_v1.K8sIoApimachineryPkgApisMetaV1FieldsV1()
        pass


if __name__ == '__main__':
    unittest.main()
