# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.k8s_io_api_core_v1_persistent_volume_claim_volume_source import K8sIoApiCoreV1PersistentVolumeClaimVolumeSource


class TestK8sIoApiCoreV1PersistentVolumeClaimVolumeSource(unittest.TestCase):
    """ K8sIoApiCoreV1PersistentVolumeClaimVolumeSource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8sIoApiCoreV1PersistentVolumeClaimVolumeSource(self):
        """
        Test K8sIoApiCoreV1PersistentVolumeClaimVolumeSource
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.k8s_io_api_core_v1_persistent_volume_claim_volume_source.K8sIoApiCoreV1PersistentVolumeClaimVolumeSource()
        pass


if __name__ == '__main__':
    unittest.main()
