# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_user_password_access_credential_source import V1UserPasswordAccessCredentialSource


class TestV1UserPasswordAccessCredentialSource(unittest.TestCase):
    """ V1UserPasswordAccessCredentialSource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1UserPasswordAccessCredentialSource(self):
        """
        Test V1UserPasswordAccessCredentialSource
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_user_password_access_credential_source.V1UserPasswordAccessCredentialSource()
        pass


if __name__ == '__main__':
    unittest.main()
