# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1alpha1_migration_policy import V1alpha1MigrationPolicy


class TestV1alpha1MigrationPolicy(unittest.TestCase):
    """ V1alpha1MigrationPolicy unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1MigrationPolicy(self):
        """
        Test V1alpha1MigrationPolicy
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1alpha1_migration_policy.V1alpha1MigrationPolicy()
        pass


if __name__ == '__main__':
    unittest.main()
