# coding: utf-8

"""


    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version:

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.v1_graphics import V1Graphics


class TestV1Graphics(unittest.TestCase):
    """ V1Graphics unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Graphics(self):
        """
        Test V1Graphics
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.v1_graphics.V1Graphics()
        pass


if __name__ == '__main__':
    unittest.main()
