# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.k8s_io_api_core_v1_topology_spread_constraint import K8sIoApiCoreV1TopologySpreadConstraint


class TestK8sIoApiCoreV1TopologySpreadConstraint(unittest.TestCase):
    """ K8sIoApiCoreV1TopologySpreadConstraint unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8sIoApiCoreV1TopologySpreadConstraint(self):
        """
        Test K8sIoApiCoreV1TopologySpreadConstraint
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.k8s_io_api_core_v1_topology_spread_constraint.K8sIoApiCoreV1TopologySpreadConstraint()
        pass


if __name__ == '__main__':
    unittest.main()
