# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_virtual_machine_instance_replica_set_status import V1VirtualMachineInstanceReplicaSetStatus


class TestV1VirtualMachineInstanceReplicaSetStatus(unittest.TestCase):
    """ V1VirtualMachineInstanceReplicaSetStatus unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1VirtualMachineInstanceReplicaSetStatus(self):
        """
        Test V1VirtualMachineInstanceReplicaSetStatus
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_virtual_machine_instance_replica_set_status.V1VirtualMachineInstanceReplicaSetStatus()
        pass


if __name__ == '__main__':
    unittest.main()
