# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_pci_host_device import V1PciHostDevice


class TestV1PciHostDevice(unittest.TestCase):
    """ V1PciHostDevice unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PciHostDevice(self):
        """
        Test V1PciHostDevice
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_pci_host_device.V1PciHostDevice()
        pass


if __name__ == '__main__':
    unittest.main()
