# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.intstr_int_or_string import IntstrIntOrString


class TestIntstrIntOrString(unittest.TestCase):
    """ IntstrIntOrString unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntstrIntOrString(self):
        """
        Test IntstrIntOrString
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.intstr_int_or_string.IntstrIntOrString()
        pass


if __name__ == '__main__':
    unittest.main()
