# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kubevirt
from kubevirt.rest import ApiException
from kubevirt.models.v1_instancetype_status_ref import V1InstancetypeStatusRef


class TestV1InstancetypeStatusRef(unittest.TestCase):
    """ V1InstancetypeStatusRef unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1InstancetypeStatusRef(self):
        """
        Test V1InstancetypeStatusRef
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = kubevirt.models.v1_instancetype_status_ref.V1InstancetypeStatusRef()
        pass


if __name__ == '__main__':
    unittest.main()
