# coding: utf-8

"""


    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version:

    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1SysInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, system=None, bios=None, base_board=None):
        """
        V1SysInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'system': 'list[V1Entry]',
            'bios': 'list[V1Entry]',
            'base_board': 'list[V1Entry]'
        }

        self.attribute_map = {
            'type': 'type',
            'system': 'system',
            'bios': 'bios',
            'base_board': 'baseBoard'
        }

        self._type = type
        self._system = system
        self._bios = bios
        self._base_board = base_board

    @property
    def type(self):
        """
        Gets the type of this V1SysInfo.


        :return: The type of this V1SysInfo.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this V1SysInfo.


        :param type: The type of this V1SysInfo.
        :type: str
        """

        self._type = type

    @property
    def system(self):
        """
        Gets the system of this V1SysInfo.


        :return: The system of this V1SysInfo.
        :rtype: list[V1Entry]
        """
        return self._system

    @system.setter
    def system(self, system):
        """
        Sets the system of this V1SysInfo.


        :param system: The system of this V1SysInfo.
        :type: list[V1Entry]
        """

        self._system = system

    @property
    def bios(self):
        """
        Gets the bios of this V1SysInfo.


        :return: The bios of this V1SysInfo.
        :rtype: list[V1Entry]
        """
        return self._bios

    @bios.setter
    def bios(self, bios):
        """
        Sets the bios of this V1SysInfo.


        :param bios: The bios of this V1SysInfo.
        :type: list[V1Entry]
        """

        self._bios = bios

    @property
    def base_board(self):
        """
        Gets the base_board of this V1SysInfo.


        :return: The base_board of this V1SysInfo.
        :rtype: list[V1Entry]
        """
        return self._base_board

    @base_board.setter
    def base_board(self, base_board):
        """
        Sets the base_board of this V1SysInfo.


        :param base_board: The base_board of this V1SysInfo.
        :type: list[V1Entry]
        """

        self._base_board = base_board

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
