# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1Filesystem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'virtiofs': 'V1FilesystemVirtiofs'
    }

    attribute_map = {
        'name': 'name',
        'virtiofs': 'virtiofs'
    }

    def __init__(self, name='', virtiofs=None):
        """
        V1Filesystem - a model defined in Swagger
        """

        self._name = None
        self._virtiofs = None

        self.name = name
        self.virtiofs = virtiofs

    @property
    def name(self):
        """
        Gets the name of this V1Filesystem.
        Name is the device name

        :return: The name of this V1Filesystem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this V1Filesystem.
        Name is the device name

        :param name: The name of this V1Filesystem.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def virtiofs(self):
        """
        Gets the virtiofs of this V1Filesystem.
        Virtiofs is supported

        :return: The virtiofs of this V1Filesystem.
        :rtype: V1FilesystemVirtiofs
        """
        return self._virtiofs

    @virtiofs.setter
    def virtiofs(self, virtiofs):
        """
        Sets the virtiofs of this V1Filesystem.
        Virtiofs is supported

        :param virtiofs: The virtiofs of this V1Filesystem.
        :type: V1FilesystemVirtiofs
        """
        if virtiofs is None:
            raise ValueError("Invalid value for `virtiofs`, must not be `None`")

        self._virtiofs = virtiofs

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1Filesystem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
