# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1PermittedHostDevices(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mediated_devices': 'list[V1MediatedHostDevice]',
        'pci_host_devices': 'list[V1PciHostDevice]',
        'usb': 'list[V1USBHostDevice]'
    }

    attribute_map = {
        'mediated_devices': 'mediatedDevices',
        'pci_host_devices': 'pciHostDevices',
        'usb': 'usb'
    }

    def __init__(self, mediated_devices=None, pci_host_devices=None, usb=None):
        """
        V1PermittedHostDevices - a model defined in Swagger
        """

        self._mediated_devices = None
        self._pci_host_devices = None
        self._usb = None

        if mediated_devices is not None:
          self.mediated_devices = mediated_devices
        if pci_host_devices is not None:
          self.pci_host_devices = pci_host_devices
        if usb is not None:
          self.usb = usb

    @property
    def mediated_devices(self):
        """
        Gets the mediated_devices of this V1PermittedHostDevices.

        :return: The mediated_devices of this V1PermittedHostDevices.
        :rtype: list[V1MediatedHostDevice]
        """
        return self._mediated_devices

    @mediated_devices.setter
    def mediated_devices(self, mediated_devices):
        """
        Sets the mediated_devices of this V1PermittedHostDevices.

        :param mediated_devices: The mediated_devices of this V1PermittedHostDevices.
        :type: list[V1MediatedHostDevice]
        """

        self._mediated_devices = mediated_devices

    @property
    def pci_host_devices(self):
        """
        Gets the pci_host_devices of this V1PermittedHostDevices.

        :return: The pci_host_devices of this V1PermittedHostDevices.
        :rtype: list[V1PciHostDevice]
        """
        return self._pci_host_devices

    @pci_host_devices.setter
    def pci_host_devices(self, pci_host_devices):
        """
        Sets the pci_host_devices of this V1PermittedHostDevices.

        :param pci_host_devices: The pci_host_devices of this V1PermittedHostDevices.
        :type: list[V1PciHostDevice]
        """

        self._pci_host_devices = pci_host_devices

    @property
    def usb(self):
        """
        Gets the usb of this V1PermittedHostDevices.

        :return: The usb of this V1PermittedHostDevices.
        :rtype: list[V1USBHostDevice]
        """
        return self._usb

    @usb.setter
    def usb(self, usb):
        """
        Sets the usb of this V1PermittedHostDevices.

        :param usb: The usb of this V1PermittedHostDevices.
        :type: list[V1USBHostDevice]
        """

        self._usb = usb

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1PermittedHostDevices):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
