# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1StallDetectorOptions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'completion_timeout_factor': 'str',
        'ewma_alpha': 'str',
        'patience_window_decay_factor': 'str',
        'precopy_possible_factor': 'str',
        'search_local_minima': 'bool',
        'stall_margin': 'int',
        'stall_progress_timeout': 'int',
        'switchover_timeout': 'int'
    }

    attribute_map = {
        'completion_timeout_factor': 'completionTimeoutFactor',
        'ewma_alpha': 'ewmaAlpha',
        'patience_window_decay_factor': 'patienceWindowDecayFactor',
        'precopy_possible_factor': 'precopyPossibleFactor',
        'search_local_minima': 'searchLocalMinima',
        'stall_margin': 'stallMargin',
        'stall_progress_timeout': 'stallProgressTimeout',
        'switchover_timeout': 'switchoverTimeout'
    }

    def __init__(self, completion_timeout_factor=None, ewma_alpha=None, patience_window_decay_factor=None, precopy_possible_factor=None, search_local_minima=None, stall_margin=None, stall_progress_timeout=None, switchover_timeout=None):
        """
        V1StallDetectorOptions - a model defined in Swagger
        """

        self._completion_timeout_factor = None
        self._ewma_alpha = None
        self._patience_window_decay_factor = None
        self._precopy_possible_factor = None
        self._search_local_minima = None
        self._stall_margin = None
        self._stall_progress_timeout = None
        self._switchover_timeout = None

        if completion_timeout_factor is not None:
          self.completion_timeout_factor = completion_timeout_factor
        if ewma_alpha is not None:
          self.ewma_alpha = ewma_alpha
        if patience_window_decay_factor is not None:
          self.patience_window_decay_factor = patience_window_decay_factor
        if precopy_possible_factor is not None:
          self.precopy_possible_factor = precopy_possible_factor
        if search_local_minima is not None:
          self.search_local_minima = search_local_minima
        if stall_margin is not None:
          self.stall_margin = stall_margin
        if stall_progress_timeout is not None:
          self.stall_progress_timeout = stall_progress_timeout
        if switchover_timeout is not None:
          self.switchover_timeout = switchover_timeout

    @property
    def completion_timeout_factor(self):
        """
        Gets the completion_timeout_factor of this V1StallDetectorOptions.
        CompletionTimeoutFactor multiplies the computed migration completion timeout to determine the total time budget for deciding whether a forced switchover can still finish in time, and to extend the abort deadline after initiating a completion-timeout-driven switchover. Defaults to \"2\".

        :return: The completion_timeout_factor of this V1StallDetectorOptions.
        :rtype: str
        """
        return self._completion_timeout_factor

    @completion_timeout_factor.setter
    def completion_timeout_factor(self, completion_timeout_factor):
        """
        Sets the completion_timeout_factor of this V1StallDetectorOptions.
        CompletionTimeoutFactor multiplies the computed migration completion timeout to determine the total time budget for deciding whether a forced switchover can still finish in time, and to extend the abort deadline after initiating a completion-timeout-driven switchover. Defaults to \"2\".

        :param completion_timeout_factor: The completion_timeout_factor of this V1StallDetectorOptions.
        :type: str
        """

        self._completion_timeout_factor = completion_timeout_factor

    @property
    def ewma_alpha(self):
        """
        Gets the ewma_alpha of this V1StallDetectorOptions.
        EwmaAlpha is the smoothing factor for the exponentially weighted moving average of observed migration bandwidth. Must be in the range (0, 1]; zero is invalid because the estimate would never incorporate new samples. Higher values weight recent samples more heavily. Defaults to \"0.4\".

        :return: The ewma_alpha of this V1StallDetectorOptions.
        :rtype: str
        """
        return self._ewma_alpha

    @ewma_alpha.setter
    def ewma_alpha(self, ewma_alpha):
        """
        Sets the ewma_alpha of this V1StallDetectorOptions.
        EwmaAlpha is the smoothing factor for the exponentially weighted moving average of observed migration bandwidth. Must be in the range (0, 1]; zero is invalid because the estimate would never incorporate new samples. Higher values weight recent samples more heavily. Defaults to \"0.4\".

        :param ewma_alpha: The ewma_alpha of this V1StallDetectorOptions.
        :type: str
        """

        self._ewma_alpha = ewma_alpha

    @property
    def patience_window_decay_factor(self):
        """
        Gets the patience_window_decay_factor of this V1StallDetectorOptions.
        PatienceWindowDecayFactor is the factor by which the relaxation patience window is multiplied after each best-remaining-bytes relaxation step. Defaults to \"0.5\".

        :return: The patience_window_decay_factor of this V1StallDetectorOptions.
        :rtype: str
        """
        return self._patience_window_decay_factor

    @patience_window_decay_factor.setter
    def patience_window_decay_factor(self, patience_window_decay_factor):
        """
        Sets the patience_window_decay_factor of this V1StallDetectorOptions.
        PatienceWindowDecayFactor is the factor by which the relaxation patience window is multiplied after each best-remaining-bytes relaxation step. Defaults to \"0.5\".

        :param patience_window_decay_factor: The patience_window_decay_factor of this V1StallDetectorOptions.
        :type: str
        """

        self._patience_window_decay_factor = patience_window_decay_factor

    @property
    def precopy_possible_factor(self):
        """
        Gets the precopy_possible_factor of this V1StallDetectorOptions.
        PrecopyPossibleFactor is the maximum factor by which estimated downtime may exceed MaxDowntime while still attempting a soft stop-and-copy instead of aborting the migration. Defaults to \"1.5\".

        :return: The precopy_possible_factor of this V1StallDetectorOptions.
        :rtype: str
        """
        return self._precopy_possible_factor

    @precopy_possible_factor.setter
    def precopy_possible_factor(self, precopy_possible_factor):
        """
        Sets the precopy_possible_factor of this V1StallDetectorOptions.
        PrecopyPossibleFactor is the maximum factor by which estimated downtime may exceed MaxDowntime while still attempting a soft stop-and-copy instead of aborting the migration. Defaults to \"1.5\".

        :param precopy_possible_factor: The precopy_possible_factor of this V1StallDetectorOptions.
        :type: str
        """

        self._precopy_possible_factor = precopy_possible_factor

    @property
    def search_local_minima(self):
        """
        Gets the search_local_minima of this V1StallDetectorOptions.
        SearchLocalMinima controls whether convergence actions are delayed until remaining bytes reach a local minimum near the best observed value. When false, actions may trigger as soon as a stall is detected. Defaults to true.

        :return: The search_local_minima of this V1StallDetectorOptions.
        :rtype: bool
        """
        return self._search_local_minima

    @search_local_minima.setter
    def search_local_minima(self, search_local_minima):
        """
        Sets the search_local_minima of this V1StallDetectorOptions.
        SearchLocalMinima controls whether convergence actions are delayed until remaining bytes reach a local minimum near the best observed value. When false, actions may trigger as soon as a stall is detected. Defaults to true.

        :param search_local_minima: The search_local_minima of this V1StallDetectorOptions.
        :type: bool
        """

        self._search_local_minima = search_local_minima

    @property
    def stall_margin(self):
        """
        Gets the stall_margin of this V1StallDetectorOptions.
        StallMargin is the fractional tolerance, expressed as a percentage, used when comparing remaining migration bytes against the best observed value to detect stalls and local minima. A stall is reported when remaining bytes stay above (1 - StallMargin/100) of the outside-window minimum. Defaults to 4.

        :return: The stall_margin of this V1StallDetectorOptions.
        :rtype: int
        """
        return self._stall_margin

    @stall_margin.setter
    def stall_margin(self, stall_margin):
        """
        Sets the stall_margin of this V1StallDetectorOptions.
        StallMargin is the fractional tolerance, expressed as a percentage, used when comparing remaining migration bytes against the best observed value to detect stalls and local minima. A stall is reported when remaining bytes stay above (1 - StallMargin/100) of the outside-window minimum. Defaults to 4.

        :param stall_margin: The stall_margin of this V1StallDetectorOptions.
        :type: int
        """

        self._stall_margin = stall_margin

    @property
    def stall_progress_timeout(self):
        """
        Gets the stall_progress_timeout of this V1StallDetectorOptions.
        StallProgressTimeout is the duration in seconds of the sliding window used to track minimum remaining-bytes and detect when migration progress has stalled. Defaults to 40.

        :return: The stall_progress_timeout of this V1StallDetectorOptions.
        :rtype: int
        """
        return self._stall_progress_timeout

    @stall_progress_timeout.setter
    def stall_progress_timeout(self, stall_progress_timeout):
        """
        Sets the stall_progress_timeout of this V1StallDetectorOptions.
        StallProgressTimeout is the duration in seconds of the sliding window used to track minimum remaining-bytes and detect when migration progress has stalled. Defaults to 40.

        :param stall_progress_timeout: The stall_progress_timeout of this V1StallDetectorOptions.
        :type: int
        """

        self._stall_progress_timeout = stall_progress_timeout

    @property
    def switchover_timeout(self):
        """
        Gets the switchover_timeout of this V1StallDetectorOptions.
        SwitchoverTimeout is the duration in seconds allowed for a stop-and-copy or post-copy switchover to complete after being triggered before the migration is aborted. Defaults to 60.

        :return: The switchover_timeout of this V1StallDetectorOptions.
        :rtype: int
        """
        return self._switchover_timeout

    @switchover_timeout.setter
    def switchover_timeout(self, switchover_timeout):
        """
        Sets the switchover_timeout of this V1StallDetectorOptions.
        SwitchoverTimeout is the duration in seconds allowed for a stop-and-copy or post-copy switchover to complete after being triggered before the migration is aborted. Defaults to 60.

        :param switchover_timeout: The switchover_timeout of this V1StallDetectorOptions.
        :type: int
        """

        self._switchover_timeout = switchover_timeout

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1StallDetectorOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
