# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1TopologyHints(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tsc_frequency': 'int'
    }

    attribute_map = {
        'tsc_frequency': 'tscFrequency'
    }

    def __init__(self, tsc_frequency=None):
        """
        V1TopologyHints - a model defined in Swagger
        """

        self._tsc_frequency = None

        if tsc_frequency is not None:
          self.tsc_frequency = tsc_frequency

    @property
    def tsc_frequency(self):
        """
        Gets the tsc_frequency of this V1TopologyHints.

        :return: The tsc_frequency of this V1TopologyHints.
        :rtype: int
        """
        return self._tsc_frequency

    @tsc_frequency.setter
    def tsc_frequency(self, tsc_frequency):
        """
        Sets the tsc_frequency of this V1TopologyHints.

        :param tsc_frequency: The tsc_frequency of this V1TopologyHints.
        :type: int
        """

        self._tsc_frequency = tsc_frequency

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1TopologyHints):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
