# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1VolumeSnapshotStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'name': 'str',
        'reason': 'str'
    }

    attribute_map = {
        'enabled': 'enabled',
        'name': 'name',
        'reason': 'reason'
    }

    def __init__(self, enabled=None, name=None, reason=None):
        """
        V1VolumeSnapshotStatus - a model defined in Swagger
        """

        self._enabled = None
        self._name = None
        self._reason = None

        self.enabled = enabled
        self.name = name
        if reason is not None:
          self.reason = reason

    @property
    def enabled(self):
        """
        Gets the enabled of this V1VolumeSnapshotStatus.
        True if the volume supports snapshotting

        :return: The enabled of this V1VolumeSnapshotStatus.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this V1VolumeSnapshotStatus.
        True if the volume supports snapshotting

        :param enabled: The enabled of this V1VolumeSnapshotStatus.
        :type: bool
        """
        if enabled is None:
            raise ValueError("Invalid value for `enabled`, must not be `None`")

        self._enabled = enabled

    @property
    def name(self):
        """
        Gets the name of this V1VolumeSnapshotStatus.
        Volume name

        :return: The name of this V1VolumeSnapshotStatus.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this V1VolumeSnapshotStatus.
        Volume name

        :param name: The name of this V1VolumeSnapshotStatus.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def reason(self):
        """
        Gets the reason of this V1VolumeSnapshotStatus.
        Empty if snapshotting is enabled, contains reason otherwise

        :return: The reason of this V1VolumeSnapshotStatus.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """
        Sets the reason of this V1VolumeSnapshotStatus.
        Empty if snapshotting is enabled, contains reason otherwise

        :param reason: The reason of this V1VolumeSnapshotStatus.
        :type: str
        """

        self._reason = reason

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1VolumeSnapshotStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
