# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1alpha1BackupOptions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'backup_name': 'str',
        'backup_start_time': 'K8sIoApimachineryPkgApisMetaV1Time',
        'cmd': 'str',
        'incremental': 'str',
        'mode': 'str',
        'push_path': 'str',
        'skip_quiesce': 'bool'
    }

    attribute_map = {
        'backup_name': 'backupName',
        'backup_start_time': 'backupStartTime',
        'cmd': 'cmd',
        'incremental': 'incremental',
        'mode': 'mode',
        'push_path': 'pushPath',
        'skip_quiesce': 'skipQuiesce'
    }

    def __init__(self, backup_name=None, backup_start_time=None, cmd=None, incremental=None, mode=None, push_path=None, skip_quiesce=None):
        """
        V1alpha1BackupOptions - a model defined in Swagger
        """

        self._backup_name = None
        self._backup_start_time = None
        self._cmd = None
        self._incremental = None
        self._mode = None
        self._push_path = None
        self._skip_quiesce = None

        if backup_name is not None:
          self.backup_name = backup_name
        if backup_start_time is not None:
          self.backup_start_time = backup_start_time
        if cmd is not None:
          self.cmd = cmd
        if incremental is not None:
          self.incremental = incremental
        if mode is not None:
          self.mode = mode
        if push_path is not None:
          self.push_path = push_path
        if skip_quiesce is not None:
          self.skip_quiesce = skip_quiesce

    @property
    def backup_name(self):
        """
        Gets the backup_name of this V1alpha1BackupOptions.

        :return: The backup_name of this V1alpha1BackupOptions.
        :rtype: str
        """
        return self._backup_name

    @backup_name.setter
    def backup_name(self, backup_name):
        """
        Sets the backup_name of this V1alpha1BackupOptions.

        :param backup_name: The backup_name of this V1alpha1BackupOptions.
        :type: str
        """

        self._backup_name = backup_name

    @property
    def backup_start_time(self):
        """
        Gets the backup_start_time of this V1alpha1BackupOptions.

        :return: The backup_start_time of this V1alpha1BackupOptions.
        :rtype: K8sIoApimachineryPkgApisMetaV1Time
        """
        return self._backup_start_time

    @backup_start_time.setter
    def backup_start_time(self, backup_start_time):
        """
        Sets the backup_start_time of this V1alpha1BackupOptions.

        :param backup_start_time: The backup_start_time of this V1alpha1BackupOptions.
        :type: K8sIoApimachineryPkgApisMetaV1Time
        """

        self._backup_start_time = backup_start_time

    @property
    def cmd(self):
        """
        Gets the cmd of this V1alpha1BackupOptions.

        :return: The cmd of this V1alpha1BackupOptions.
        :rtype: str
        """
        return self._cmd

    @cmd.setter
    def cmd(self, cmd):
        """
        Sets the cmd of this V1alpha1BackupOptions.

        :param cmd: The cmd of this V1alpha1BackupOptions.
        :type: str
        """

        self._cmd = cmd

    @property
    def incremental(self):
        """
        Gets the incremental of this V1alpha1BackupOptions.

        :return: The incremental of this V1alpha1BackupOptions.
        :rtype: str
        """
        return self._incremental

    @incremental.setter
    def incremental(self, incremental):
        """
        Sets the incremental of this V1alpha1BackupOptions.

        :param incremental: The incremental of this V1alpha1BackupOptions.
        :type: str
        """

        self._incremental = incremental

    @property
    def mode(self):
        """
        Gets the mode of this V1alpha1BackupOptions.

        :return: The mode of this V1alpha1BackupOptions.
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """
        Sets the mode of this V1alpha1BackupOptions.

        :param mode: The mode of this V1alpha1BackupOptions.
        :type: str
        """

        self._mode = mode

    @property
    def push_path(self):
        """
        Gets the push_path of this V1alpha1BackupOptions.

        :return: The push_path of this V1alpha1BackupOptions.
        :rtype: str
        """
        return self._push_path

    @push_path.setter
    def push_path(self, push_path):
        """
        Sets the push_path of this V1alpha1BackupOptions.

        :param push_path: The push_path of this V1alpha1BackupOptions.
        :type: str
        """

        self._push_path = push_path

    @property
    def skip_quiesce(self):
        """
        Gets the skip_quiesce of this V1alpha1BackupOptions.

        :return: The skip_quiesce of this V1alpha1BackupOptions.
        :rtype: bool
        """
        return self._skip_quiesce

    @skip_quiesce.setter
    def skip_quiesce(self, skip_quiesce):
        """
        Sets the skip_quiesce of this V1alpha1BackupOptions.

        :param skip_quiesce: The skip_quiesce of this V1alpha1BackupOptions.
        :type: bool
        """

        self._skip_quiesce = skip_quiesce

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1alpha1BackupOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
