# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1beta1DataVolumeSourceImageIO(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cert_config_map': 'str',
        'disk_id': 'str',
        'secret_ref': 'str',
        'url': 'str'
    }

    attribute_map = {
        'cert_config_map': 'certConfigMap',
        'disk_id': 'diskId',
        'secret_ref': 'secretRef',
        'url': 'url'
    }

    def __init__(self, cert_config_map=None, disk_id='', secret_ref=None, url=''):
        """
        V1beta1DataVolumeSourceImageIO - a model defined in Swagger
        """

        self._cert_config_map = None
        self._disk_id = None
        self._secret_ref = None
        self._url = None

        if cert_config_map is not None:
          self.cert_config_map = cert_config_map
        self.disk_id = disk_id
        if secret_ref is not None:
          self.secret_ref = secret_ref
        self.url = url

    @property
    def cert_config_map(self):
        """
        Gets the cert_config_map of this V1beta1DataVolumeSourceImageIO.
        CertConfigMap provides a reference to the CA cert

        :return: The cert_config_map of this V1beta1DataVolumeSourceImageIO.
        :rtype: str
        """
        return self._cert_config_map

    @cert_config_map.setter
    def cert_config_map(self, cert_config_map):
        """
        Sets the cert_config_map of this V1beta1DataVolumeSourceImageIO.
        CertConfigMap provides a reference to the CA cert

        :param cert_config_map: The cert_config_map of this V1beta1DataVolumeSourceImageIO.
        :type: str
        """

        self._cert_config_map = cert_config_map

    @property
    def disk_id(self):
        """
        Gets the disk_id of this V1beta1DataVolumeSourceImageIO.
        DiskID provides id of a disk to be imported

        :return: The disk_id of this V1beta1DataVolumeSourceImageIO.
        :rtype: str
        """
        return self._disk_id

    @disk_id.setter
    def disk_id(self, disk_id):
        """
        Sets the disk_id of this V1beta1DataVolumeSourceImageIO.
        DiskID provides id of a disk to be imported

        :param disk_id: The disk_id of this V1beta1DataVolumeSourceImageIO.
        :type: str
        """
        if disk_id is None:
            raise ValueError("Invalid value for `disk_id`, must not be `None`")

        self._disk_id = disk_id

    @property
    def secret_ref(self):
        """
        Gets the secret_ref of this V1beta1DataVolumeSourceImageIO.
        SecretRef provides the secret reference needed to access the ovirt-engine

        :return: The secret_ref of this V1beta1DataVolumeSourceImageIO.
        :rtype: str
        """
        return self._secret_ref

    @secret_ref.setter
    def secret_ref(self, secret_ref):
        """
        Sets the secret_ref of this V1beta1DataVolumeSourceImageIO.
        SecretRef provides the secret reference needed to access the ovirt-engine

        :param secret_ref: The secret_ref of this V1beta1DataVolumeSourceImageIO.
        :type: str
        """

        self._secret_ref = secret_ref

    @property
    def url(self):
        """
        Gets the url of this V1beta1DataVolumeSourceImageIO.
        URL is the URL of the ovirt-engine

        :return: The url of this V1beta1DataVolumeSourceImageIO.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this V1beta1DataVolumeSourceImageIO.
        URL is the URL of the ovirt-engine

        :param url: The url of this V1beta1DataVolumeSourceImageIO.
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")

        self._url = url

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1beta1DataVolumeSourceImageIO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
