# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1beta1MachinePreferences(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'preferred_machine_type': 'str'
    }

    attribute_map = {
        'preferred_machine_type': 'preferredMachineType'
    }

    def __init__(self, preferred_machine_type=None):
        """
        V1beta1MachinePreferences - a model defined in Swagger
        """

        self._preferred_machine_type = None

        if preferred_machine_type is not None:
          self.preferred_machine_type = preferred_machine_type

    @property
    def preferred_machine_type(self):
        """
        Gets the preferred_machine_type of this V1beta1MachinePreferences.
        PreferredMachineType optionally defines the preferred machine type to use.

        :return: The preferred_machine_type of this V1beta1MachinePreferences.
        :rtype: str
        """
        return self._preferred_machine_type

    @preferred_machine_type.setter
    def preferred_machine_type(self, preferred_machine_type):
        """
        Sets the preferred_machine_type of this V1beta1MachinePreferences.
        PreferredMachineType optionally defines the preferred machine type to use.

        :param preferred_machine_type: The preferred_machine_type of this V1beta1MachinePreferences.
        :type: str
        """

        self._preferred_machine_type = preferred_machine_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1beta1MachinePreferences):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
